name: Deploy Python app to Azure Web App - ChatbotApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App (remote build)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ChatbotApp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .



# name: Build and deploy Python app to Azure Web App - ChatbotApp

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Check out repo
#         uses: actions/checkout@v4

#       - name: Zip artifact for deployment
#         run: |
#           cd ${{ github.workspace }}
#           zip -r release.zip . -x "*.git*" "*__pycache__*" "*.pyc" "tests/*" "release.zip"
      
#       - name: Upload artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: python-app
#           path: release.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: python-app

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'ChatbotApp'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: 'release.zip'