name: Trigger DB Setup

on:
  schedule:
    - cron: '59 23 1 * *'
  workflow_dispatch:

jobs:
  trigger-db-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Flask app
        run: |
          curl -X POST https://your-app-url/trigger-database-setup \
            -H "X-Setup-Secret: ${{ secrets.SETUP_SECRET }}"